packages:
  - .
allowBuilds:
  "@parcel/watcher": true
  "@savvy-web/github-action-builder": true
  "@savvy-web/vitest": true
  better-sqlite3: true
  core-js: true
  esbuild: true
  libxmljs2: true
  msgpackr-extract: true
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.15.1+sha512-/YweRPSahFlUxa5P5sCspJ9VMyaICvZDEutIP3rPrjNEW7kJGg93lGXzJI2WMwvaTBRzOrjFGVRbTGkx6ZX30g==
